DISTFILES += \
    Makefile \
    README.md \
    TimeKeeperEvolution-1.4.plasmoid \
    package/LICENSE.GPL3 \
    package/contents/config/config.qml \
    package/contents/config/main.xml \
    package/contents/screenshot.png \
    package/contents/ui/Main.qml \
    package/contents/ui/calendar/Calendar.qml \
    package/contents/ui/calendar/calendar.png \
    package/contents/ui/calendar/calendarLongYear.png \
    package/contents/ui/calendar/calendarLongYearShadow.png \
    package/contents/ui/calendar/calendarShortYear.png \
    package/contents/ui/calendar/calendarShortYearShadow.png \
    package/contents/ui/calendar/lookingGlass.png \
    package/contents/ui/calendar/lookingGlassShadow.png \
    package/contents/ui/calendar/textBackgroundRound.png \
    package/contents/ui/clock/Clock.qml \
    package/contents/ui/clock/center.png \
    package/contents/ui/clock/centerShadow.png \
    package/contents/ui/clock/clock.png \
    package/contents/ui/clock/clockReflection.png \
    package/contents/ui/clock/clockShadow.png \
    package/contents/ui/clock/clockglass.png \
    package/contents/ui/clock/cogs/Cogs.qml \
    package/contents/ui/clock/cogs/cog.png \
    package/contents/ui/clock/cogs/cogShadow.png \
    package/contents/ui/clock/cogs/driveBand.png \
    package/contents/ui/clock/cogs/driveBandShadow.png \
    package/contents/ui/clock/cogs/wheel.png \
    package/contents/ui/clock/cogs/wheelShadow.png \
    package/contents/ui/clock/hour.png \
    package/contents/ui/clock/hourShadow.png \
    package/contents/ui/clock/minute.png \
    package/contents/ui/clock/minuteShadow.png \
    package/contents/ui/clock/second.png \
    package/contents/ui/clock/textBackground.png \
    package/contents/ui/clock/timeRing.png \
    package/contents/ui/configplasma/cfgMain.qml \
    package/contents/ui/font/Engravers_MT.ttf \
    package/contents/ui/sounds/Sounds.qml \
    package/contents/ui/sounds/grandfather-clock/bigWheelCog.wav \
    package/contents/ui/sounds/grandfather-clock/chime.wav \
    package/contents/ui/sounds/grandfather-clock/clockMechanismCog.wav \
    package/contents/ui/sounds/grandfather-clock/hourCog.wav \
    package/contents/ui/sounds/grandfather-clock/minutesCog.wav \
    package/contents/ui/sounds/grandfather-clock/secondsCogEven.wav \
    package/contents/ui/sounds/grandfather-clock/secondsCogOdd.wav \
    package/contents/ui/sounds/smooth-clock/bigWheelCog.wav \
    package/contents/ui/sounds/smooth-clock/chime.wav \
    package/contents/ui/sounds/smooth-clock/clockMechanismCog.wav \
    package/contents/ui/sounds/smooth-clock/hourCog.wav \
    package/contents/ui/sounds/smooth-clock/minutesCog.wav \
    package/contents/ui/sounds/smooth-clock/secondsCogEven.wav \
    package/contents/ui/sounds/smooth-clock/secondsCogOdd.wav \
    package/contents/ui/sounds/switching.wav \
    package/contents/ui/sounds/wooden-clock/bigWheelCog.wav \
    package/contents/ui/sounds/wooden-clock/chime.wav \
    package/contents/ui/sounds/wooden-clock/clockMechanismCog.wav \
    package/contents/ui/sounds/wooden-clock/hourCog.wav \
    package/contents/ui/sounds/wooden-clock/minutesCog.wav \
    package/contents/ui/sounds/wooden-clock/secondsCogEven.wav \
    package/contents/ui/sounds/wooden-clock/secondsCogOdd.wav \
    package/contents/ui/timekeeper/Timekeeper.qml \
    package/contents/ui/timekeeper/frame/backgrounds/backSky.png \
    package/contents/ui/timekeeper/frame/backgrounds/glassImmage0.png \
    package/contents/ui/timekeeper/frame/backgrounds/glassImmage1.png \
    package/contents/ui/timekeeper/frame/backgrounds/glassImmage2.png \
    package/contents/ui/timekeeper/frame/backgrounds/glassImmage3.png \
    package/contents/ui/timekeeper/frame/backgrounds/glassImmage4.png \
    package/contents/ui/timekeeper/frame/backgrounds/glassImmage5.png \
    package/contents/ui/timekeeper/frame/backgrounds/glassImmage6.png \
    package/contents/ui/timekeeper/frame/backgrounds/glassTransparent.png \
    package/contents/ui/timekeeper/frame/counterWheel.png \
    package/contents/ui/timekeeper/frame/innerFrame.png \
    package/contents/ui/timekeeper/frame/innerMetalFrame.png \
    package/contents/ui/timekeeper/frame/knob.png \
    package/contents/ui/timekeeper/frame/monthRing.png \
    package/contents/ui/timekeeper/frame/woodSurround.png \
    package/contents/ui/timekeeper/orrery/Orrery.qml \
    package/contents/ui/timekeeper/orrery/earth/Earth.qml \
    package/contents/ui/timekeeper/orrery/earth/animation/earth0.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth1.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth10.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth11.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth12.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth13.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth14.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth15.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth16.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth17.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth18.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth19.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth2.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth20.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth21.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth22.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth23.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth24.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth25.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth26.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth27.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth28.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth29.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth3.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth30.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth31.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth32.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth33.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth34.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth35.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth36.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth37.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth38.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth39.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth4.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth40.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth41.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth42.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth43.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth44.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth45.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth46.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth47.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth48.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth49.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth5.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth50.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth51.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth52.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth53.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth54.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth55.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth56.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth57.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth58.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth59.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth6.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth60.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth61.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth62.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth63.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth64.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth65.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth66.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth67.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth68.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth69.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth7.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth70.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth71.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth72.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth73.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth74.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth75.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth76.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth77.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth78.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth79.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth8.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth80.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth81.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth82.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth83.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth84.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth85.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth86.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth87.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth88.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth89.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth9.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth90.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth91.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth92.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth93.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth94.png \
    package/contents/ui/timekeeper/orrery/earth/animation/earth95.png \
    package/contents/ui/timekeeper/orrery/earth/earthTop.png \
    package/contents/ui/timekeeper/orrery/earth/moon/Moon.qml \
    package/contents/ui/timekeeper/orrery/earth/moon/luna_1.svg \
    package/contents/ui/timekeeper/orrery/earth/moon/luna_10.svg \
    package/contents/ui/timekeeper/orrery/earth/moon/luna_11.svg \
    package/contents/ui/timekeeper/orrery/earth/moon/luna_12.svg \
    package/contents/ui/timekeeper/orrery/earth/moon/luna_13.svg \
    package/contents/ui/timekeeper/orrery/earth/moon/luna_14.svg \
    package/contents/ui/timekeeper/orrery/earth/moon/luna_15.svg \
    package/contents/ui/timekeeper/orrery/earth/moon/luna_16.svg \
    package/contents/ui/timekeeper/orrery/earth/moon/luna_17.svg \
    package/contents/ui/timekeeper/orrery/earth/moon/luna_18.svg \
    package/contents/ui/timekeeper/orrery/earth/moon/luna_19.svg \
    package/contents/ui/timekeeper/orrery/earth/moon/luna_2.svg \
    package/contents/ui/timekeeper/orrery/earth/moon/luna_20.svg \
    package/contents/ui/timekeeper/orrery/earth/moon/luna_21.svg \
    package/contents/ui/timekeeper/orrery/earth/moon/luna_22.svg \
    package/contents/ui/timekeeper/orrery/earth/moon/luna_23.svg \
    package/contents/ui/timekeeper/orrery/earth/moon/luna_24.svg \
    package/contents/ui/timekeeper/orrery/earth/moon/luna_25.svg \
    package/contents/ui/timekeeper/orrery/earth/moon/luna_26.svg \
    package/contents/ui/timekeeper/orrery/earth/moon/luna_27.svg \
    package/contents/ui/timekeeper/orrery/earth/moon/luna_28.svg \
    package/contents/ui/timekeeper/orrery/earth/moon/luna_29.svg \
    package/contents/ui/timekeeper/orrery/earth/moon/luna_3.svg \
    package/contents/ui/timekeeper/orrery/earth/moon/luna_4.svg \
    package/contents/ui/timekeeper/orrery/earth/moon/luna_5.svg \
    package/contents/ui/timekeeper/orrery/earth/moon/luna_6.svg \
    package/contents/ui/timekeeper/orrery/earth/moon/luna_7.svg \
    package/contents/ui/timekeeper/orrery/earth/moon/luna_8.svg \
    package/contents/ui/timekeeper/orrery/earth/moon/luna_9.svg \
    package/contents/ui/timekeeper/orrery/earth/moon/moonBigShadow.png \
    package/contents/ui/timekeeper/orrery/earth/moon/moonUnderShadow.png \
    package/contents/ui/timekeeper/orrery/earth/moon/phase.js \
    package/contents/ui/timekeeper/orrery/jupiter/Jupiter.qml \
    package/contents/ui/timekeeper/orrery/jupiter/calisto/calistoFront.png \
    package/contents/ui/timekeeper/orrery/jupiter/europa/europaFront.png \
    package/contents/ui/timekeeper/orrery/jupiter/ganymede/ganymedeFront.png \
    package/contents/ui/timekeeper/orrery/jupiter/io/ioFront.png \
    package/contents/ui/timekeeper/orrery/jupiter/jupiter.js \
    package/contents/ui/timekeeper/orrery/jupiter/jupiterFront.png \
    package/contents/ui/timekeeper/orrery/jupiter/jupiterTop.png \
    package/contents/ui/timekeeper/orrery/mars/Mars.qml \
    package/contents/ui/timekeeper/orrery/mars/marsFront.png \
    package/contents/ui/timekeeper/orrery/mars/marsTop.png \
    package/contents/ui/timekeeper/orrery/mercury/Mercury.qml \
    package/contents/ui/timekeeper/orrery/mercury/mercuryFront.png \
    package/contents/ui/timekeeper/orrery/mercury/mercuryTop.png \
    package/contents/ui/timekeeper/orrery/neptune/Neptune.qml \
    package/contents/ui/timekeeper/orrery/neptune/neptuneFront.png \
    package/contents/ui/timekeeper/orrery/neptune/neptuneTop.png \
    package/contents/ui/timekeeper/orrery/planets.js \
    package/contents/ui/timekeeper/orrery/saturn/Saturn.qml \
    package/contents/ui/timekeeper/orrery/saturn/saturnFront.png \
    package/contents/ui/timekeeper/orrery/saturn/saturnTop.png \
    package/contents/ui/timekeeper/orrery/sun/Sun.qml \
    package/contents/ui/timekeeper/orrery/sun/sunTop.png \
    package/contents/ui/timekeeper/orrery/underShadow.png \
    package/contents/ui/timekeeper/orrery/uranus/Uranus.qml \
    package/contents/ui/timekeeper/orrery/uranus/uranusFront.png \
    package/contents/ui/timekeeper/orrery/uranus/uranusTop.png \
    package/contents/ui/timekeeper/orrery/venus/Venus.qml \
    package/contents/ui/timekeeper/orrery/venus/venusFront.png \
    package/contents/ui/timekeeper/orrery/venus/venusTop.png \
    package/metadata.desktop \
    tk.jpg \
    tk.qmlproject
